### ISSUE TITLE
[ENG-1234] [Mac] Icon size does not persist when navigating away

### ISSUE THREAD

**Issue by bloodrizer** [spacedriveapp/spacedrive#1482]
### Describe the bug

Change item size in the folder settings menu. Restart the app, or simply open the settings and return back to the folder. Icon size will be reset to default. 

### Reproduction

See above.

### Expected behavior

Icon size should be persisted for the current session and all consequent sessions, either per folder or globally.

### Platform and versions

```Shell
Mac OS, v0.1.0
```

**Comment by ameer2468** [comment]
Hi, was this performed within a ephemeral location? we don't have preferences yet for ephemeral locations, however, in indexed locations we do.

We will be adding support for ephemeral soon.

**Comment by matthiasfromm** [comment]
Hi Ameer,

I can still confirm this issue in v0.1.4 on MacOS 13.4.1.

For me this happens when I set the item size in any of the Local directories, then switch to the Devices (clicking on the local device, in this case my mac). I'm not working yet with indexed/ephemeral locations (I think). The short screenrecord below shows the behaviour.

https://github.com/spacedriveapp/spacedrive/assets/2086207/4e872b0d-5eba-4dbb-88dc-7ea6d8a290af

No pressure, just wanted to provide some more feedback.

**Comment by ameer2468** [comment]
Hey Mathias, thank you for the detailed feedback.

- Indexed locations are the locations you add through the 'Add Location' button.
- Ephemeral locations are the ones of your system i.e 'Home' and 'Macintosh HD'

We recently patched a bug for preferences within indexed locations and this fix will be released very soon with a new update.

Ephemeral locations do not save preferences currently, however, they will do so soon.

**Comment by matthiasfromm** [comment]
Hi Ameer,

thanks for the explanation re. ephemeral and indexed locations. Got it!

Looking forward then, cheers!
