### ISSUE TITLE
LibraryStatistics should have an identifying relationship with Library

### ISSUE THREAD

**Issue by JediMaster25** [spacedriveapp/spacedrive#179]
### Describe the bug

Instead of using a new field to reference Library, use the primary key. I think the same happens for the SyncEvent and Client.

Also you haven't clarified my previous issues in the code with comments.
https://github.com/spacedriveapp/spacedrive/issues/161
https://github.com/spacedriveapp/spacedrive/issues/162
https://github.com/spacedriveapp/spacedrive/issues/163

### Platform and versions

```shell
Does not apply.
```

**Comment by oscartbeaumont** [comment]
Please be clearer when creating issues because you refer to a "new field" without defining its name which unnecessarily wastes the time of the reviewer.

I assume in this issue you are referring to the fact that a `Library` has a one-to-one relationship with `LibraryStatistics` and hence we should modify the code so that the `LibraryStatistics`'s primary key is the same as its corresponding `Library`'s primary key saving us from having to have a `library_id` column.
 
This seems like a reasonable point although I don't think it should be filed as a bug as it is just a different choice in design. Please keep similar discussions in the future to GitHub Discussions or Discord so the issues tracker can stay clean with actual bugs.
