### ISSUE TITLE
localhost refused to connect

### ISSUE THREAD

**Issue by Ademking** [spacedriveapp/spacedrive#24]
First of all, Nice projet! Keep up the good work 👍 

When i visit [https://www.spacedrive.app/](https://www.spacedrive.app/) There is this weired iframe thing that shows 
"localhost refused to connect."

![image](https://user-images.githubusercontent.com/12462188/165217740-84dbab19-0408-40c0-971f-c8a763bea212.png)

I think the problem is here:

![image](https://user-images.githubusercontent.com/12462188/165217928-a85b1f4d-9a3e-4d8d-98ae-5a759c683d4d.png)

**Comment by oscartbeaumont** [comment]
This is something we are already aware of and are working on but thanks for the report!

We are going to deploy a working version of the Spacedrive app which runs as part of the landing page. Currently, however, we have hardcoded the iframe to use localhost. We are having some delays getting everything deployed due to technical issues we are having with CI.

@jamiepine Should the fallback image be shown to the user even on desktop devices in the meantime?

**Comment by jamiepine** [comment]
oh shoot that shouldn't have deployed, rolled back!
