### ISSUE TITLE
[ENG-214] Flipper causes crash on android

### ISSUE THREAD

**Issue by IllusionMan1212** [spacedriveapp/spacedrive#356]
### Describe the bug

The mobile app crashes a few seconds after launch on android

### Reproduction

1. Compile debug build
   - cd into `apps/mobile` and `mkdir android/app/src/main/assets`
   - while in `apps/mobile` run `npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
   - cd into `android` and run `./gradlew assembleDebug`
   - debug apk should be built into `android/app/src/build/outputs/apk/debug/`
3. Install apk.
4. Launch app and wait for it to crash.

### Expected behavior

Expected app not to crash.

### Platform and versions

```Shell
pnpm version: `7.9.0`
cargo version: `cargo 1.62.1 (a748cf5a3 2022-06-08)`
rustc version: `1.62.1 (e092d0b6b 2022-07-16)`
OS: `Ubuntu 22.04 LTS 5.15.0-43-generic`
```

### Stack trace

```Shell
The only thing I was able to get from logcat is a lot of this
`Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 11235 (FlipperEventBas), pid 11213 (ile.development)`
```

### Additional context

This bug isn't directly caused by spacedrive itself, it's caused by `flipper` and is related to this [issue](https://github.com/facebook/flipper/issues/3284).
This can be fixed by downgrading flipper to version `0.105.0` (for the time being) as suggested on the linked issue.

**Comment by utkubakir** [comment]
Okay, I tested Flipper on Android & IOS and it works as expected!

I checked our code and couldn't find any references to Flipper so I am guessing Expo is doing some work under the hood and adding it for us and since the react-native bundler does not, it crashes.

If anyone wants to give it a try and potentially reopen this issue, switch to `mobile-library` branch (app on main doesn't bundle rn) and run `pnpm ios` or `pnpm android` instead of bundling it manually...
