### ISSUE TITLE
[MacOS] Resizing Spacedrive Using Window Manager

### ISSUE THREAD

**Issue by Soft-Bred** [spacedriveapp/spacedrive#856]
### Describe the bug

Resizing Spacedrive using a window manager does not allow Spacedrive to remember the resolution that it was set to. Resizing the window manually is okay, although moving the window after resizing it using a window manager does not work as intended.

### Reproduction

1. Install https://rectangleapp.com/
2. Set up keyboard shortcuts for Rectangle
3. Try to resize Spacedrive using rectangle.
4. Drag spacedrive around using the toolbar
5. Watch the window revert to original size.

https://github.com/spacedriveapp/spacedrive/assets/60551230/d25be29c-3d70-4383-947f-79c65b46d461

### Expected behavior

The window stays the same resolution after modified by window manager.

### Platform and versions

```Shell
©`pnpm --version && cargo --version && rustc --version`:
9.6.6

OS:
macOS 12.6.2 21G320 arm64

Chip:
Apple M1 Max

Spacedrive Version:
v0.1.0 - 2325a8c
```

**Comment by HeavenVolkoff** [comment]
This may be an underlining issue with Tauri specifically on macOS, because I can't reproduce it on Linux:

[Screencast from 2023-05-24 14-16-39.webm](https://github.com/spacedriveapp/spacedrive/assets/9082460/2527ee2c-bd64-4c8b-9e3d-78e1a7ea1dd8)

Could you test this in another Tauri based app and see if they have the same behavior?
Like [this one](https://github.com/zzzgydi/clash-verge/releases/tag/v1.3.2) or [this one](https://github.com/G07cha/pomodoro/releases/tag/v3.0.0)

**Comment by Soft-Bred** [comment]
Can confirm, Tauri issue:

https://github.com/spacedriveapp/spacedrive/assets/60551230/9269eac7-c0a9-4fa9-a8db-1a1c804ed97b

**Comment by PineappleRind** [comment]
https://github.com/spacedriveapp/spacedrive/assets/65303441/97950d59-adc8-477d-a539-47d680ba0955

I think this is Rectangle's default behaviour and not Tauri's, since other apps are affected by it
